swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 3.1.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdowasdas
      produces:
        - application/json
      responses:
        200:
          description: OK
  /api/companies/new:
    get:
      summary: Returns a fake company.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /api/users/new:
    get:
      summary: Returns a fake user.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /api/user/company:
    get: 
      summary: Returns a fake company and user.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK


